import contextlib
import io
import json
import tempfile
import textwrap
import unittest
from pathlib import Path

import support  # noqa: F401  (puts the scripts folder on sys.path)
import map_structure
import structure_report

FIXTURE = {
    "package.json": '{"dependencies": {"express": "4.19.2"}}\n',
    ".clean/roles.md": """
        ```clean-roles
        role middleware = **/middleware/**
        role service = **/services/**
        role route = **/routes/**
        signal middleware = \\(\\s*req\\b[^)]*,\\s*res\\b[^)]*,\\s*next\\b
        name service = Service$
        ```
        """,
    "src/app.js": """
        const users = require('./routes/users');
        const requestId = require('./middleware/requestId');
        """,
    "src/routes/users.js": """
        const auth = require('../services/auth');
        """,
    "src/middleware/requestId.js": """
        /** Tags each request with an id. */
        module.exports = function requestId(req, res, next) { next(); };
        """,
    "src/services/auth.js": """
        // Issues and checks session tokens.

        class AuthService {}
        function authMiddleware(req, res, next) { next(); }
        module.exports = { AuthService, authMiddleware };
        """,
    "src/services/client.generated.js": """
        // Code generated by a tool. DO NOT EDIT.
        function clientMiddleware(req, res, next) { next(); }
        module.exports = { clientMiddleware };
        """,
    "src/services/fetch.js": """
        function getUser(id) { return id; }
        function fetchUser(id) { return id; }
        module.exports = { getUser, fetchUser };
        """,
}


def write_fixture(root: Path, files: dict) -> None:
    for path, text in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(textwrap.dedent(text).lstrip("\n"), encoding="utf-8")


def run(*argv):
    output = io.StringIO()
    with contextlib.redirect_stdout(output), contextlib.redirect_stderr(io.StringIO()):
        code = map_structure.main(list(argv))
    return code, output.getvalue()


class MapStructureTest(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.root = Path(self.directory.name)
        write_fixture(self.root, FIXTURE)

    def tearDown(self):
        self.directory.cleanup()

    def test_the_middleware_in_the_service_file_is_misplaced(self):
        data = map_structure.build_map(self.root, packs=[], depth=2)
        misplaced = data["findings"]["misplaced"]
        self.assertEqual(len(misplaced), 1)
        self.assertEqual(misplaced[0]["symbol"], "authMiddleware")
        self.assertEqual(misplaced[0]["suggestion"], "src/middleware/")

    def test_synonyms_imports_and_purposes_are_recorded(self):
        data = map_structure.build_map(self.root, packs=[], depth=2)
        self.assertEqual([item["noun"] for item in data["findings"]["synonyms"]], ["user"])
        files = {entry["path"]: entry for entry in data["files"]}
        self.assertEqual(files["src/app.js"]["imports"],
                         ["src/middleware/requestId.js", "src/routes/users.js"])
        self.assertEqual(files["src/services/auth.js"]["purpose"], "Issues and checks session tokens.")
        self.assertEqual(files["src/services/auth.js"]["role"], "service")
        self.assertIn({"from": "src", "to": "src/routes", "count": 1}, data["edges"])
        self.assertNotIn("src/services/client.generated.js", files)

    def test_markdown_orders_sections_for_partial_reads(self):
        markdown = structure_report.render_markdown(
            map_structure.build_map(self.root, packs=[], depth=2), top=25)
        positions = [markdown.index(heading) for heading in
                     ("## Findings", "## Tree", "## Components", "## Files")]
        self.assertEqual(positions, sorted(positions))
        self.assertIn("| `src/services/auth.js` | service |", markdown)
        self.assertIn("`authMiddleware` !", markdown)

    def test_write_saves_both_files(self):
        code, output = run("--root", str(self.root), "--write")
        self.assertEqual(code, 0)
        self.assertTrue((self.root / ".clean" / "structure.md").is_file())
        data = json.loads((self.root / ".clean" / "structure.json").read_text(encoding="utf-8"))
        self.assertEqual(data["schema_version"], 1)
        self.assertIn("Saved", output)

    def test_path_limits_the_summary_to_a_folder(self):
        code, output = run("--root", str(self.root), "--path", "src/services")
        self.assertEqual(code, 0)
        self.assertIn("src/services/auth.js", output)
        self.assertNotIn("src/app.js", output)

    def test_recorded_pack_scopes_travel_with_the_recorded_packs(self):
        (self.root / ".clean" / "context.json").write_text(json.dumps({
            "packs": ["references/frameworks/react.md"],
            "pack_scopes": {"references/frameworks/react.md": ["web"]},
        }), encoding="utf-8")
        self.assertEqual(map_structure.stack_for(self.root, None),
                         (["references/frameworks/react.md"],
                          {"references/frameworks/react.md": ["web"]}))
        self.assertEqual(map_structure.stack_for(self.root, "frameworks/react.md"),
                         (["references/frameworks/react.md"], {}))

    def test_system_includes_draw_no_edges(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_fixture(root, {
                "src/net/ssl.h": "int ssl_init(void);\n",
                "src/core/time.h": "int now(void);\n",
                "src/app/main.c": "#include <openssl/ssl.h>\n#include <sys/time.h>\n"
                                  "int main(void)\n{\n    return 0;\n}\n",
            })
            data = map_structure.build_map(root, packs=[], depth=2)
        files = {entry["path"]: entry for entry in data["files"]}
        self.assertEqual(files["src/app/main.c"]["imports"], [])
        self.assertEqual(data["edges"], [])

    def test_a_malformed_roles_file_is_an_error(self):
        (self.root / ".clean" / "roles.md").write_text("```clean-roles\nnonsense\n```\n",
                                                       encoding="utf-8")
        code, _ = run("--root", str(self.root))
        self.assertEqual(code, 2)


if __name__ == "__main__":
    unittest.main()
