import unittest

import support  # noqa: F401  (puts the scripts folder on sys.path)
import project_files


class GlobMatchTest(unittest.TestCase):
    CASES = [
        ("**/middleware/**", "middleware/auth.ts", True),
        ("**/middleware/**", "src/middleware/auth.ts", True),
        ("**/middleware/**", "src/mymiddleware/auth.ts", False),
        ("**/*.middleware.*", "src/auth.middleware.ts", True),
        ("**/*Controller.*", "src/Web/UserController.cs", True),
        ("middleware.ts", "middleware.ts", True),
        ("middleware.ts", "src/middleware.ts", False),
        ("app/Http/Middleware/**", "app/http/middleware/Auth.php", True),
        ("src/*.ts", "src/a/b.ts", False),
        ("src\\**", "src/a/b.ts", True),
    ]

    def test_globs_span_directories_only_where_asked(self):
        for pattern, path, expected in self.CASES:
            with self.subTest(pattern=pattern, path=path):
                self.assertEqual(project_files.glob_match(pattern, path), expected)

    def test_read_text_drops_a_byte_order_mark(self):
        import tempfile
        from pathlib import Path
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "a.cs"
            path.write_bytes(b"\xef\xbb\xbfnamespace X;\n")
            self.assertEqual(project_files.read_text(path), "namespace X;\n")

    def test_generated_files_are_recognised_by_name_or_header(self):
        self.assertTrue(project_files.is_generated("Properties/Resources.Designer.cs", "class R {}"))
        self.assertTrue(project_files.is_generated("api/client.g.ts", ""))
        self.assertTrue(project_files.is_generated("proto/order_pb2.py", ""))
        self.assertTrue(project_files.is_generated(
            "src/api.ts", "// Code generated by openapi-generator. DO NOT EDIT.\nexport {}"))
        self.assertFalse(project_files.is_generated("src/designer.ts", "export const a = 1;"))

    def test_a_generated_marker_counts_only_in_the_comment_that_opens_the_file(self):
        generated = [
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage order\n",
            "# -*- coding: utf-8 -*-\n# Generated by Django 5.1 on 2026-01-02 10:00\n\n"
            "from django.db import migrations\n",
            "/*\n * Petstore API\n * NOTE: This class is auto generated by OpenAPI Generator.\n"
            " * Do not edit the class manually.\n */\nexport class Pet {}\n",
            "<?php\n\n// @generated by a tool\nnamespace App;\n",
            "// Copyright 2026 Acme\n\n// <auto-generated/>\nusing System;\n",
            "#pragma warning disable\n// <auto-generated/>\nnamespace App;\n",
        ]
        hand_written = [
            '"""Monthly invoices generated by the billing run, and their totals."""\n\n'
            "class InvoiceService:\n    pass\n",
            "export const note = 'this file is auto-generated';\n",
            "import os\n# generated by the build step\nx = 1\n",
            '#include "version_autogenerated.h"\nint main(void) { return 0; }\n',
        ]
        for text in generated:
            with self.subTest(text=text):
                self.assertTrue(project_files.is_generated("src/a.txt", text))
        for text in hand_written:
            with self.subTest(text=text):
                self.assertFalse(project_files.is_generated("src/a.txt", text))

    def test_literal_weight_ranks_the_more_specific_pattern_higher(self):
        self.assertEqual(project_files.literal_weight("**/middleware/**"), 10)
        self.assertEqual(project_files.literal_weight("**/*.middleware.*"), 12)


if __name__ == "__main__":
    unittest.main()
