import unittest

import support  # noqa: F401  (puts the scripts folder on sys.path)
import project_files


class GlobMatchTest(unittest.TestCase):
    CASES = [
        ("**/middleware/**", "middleware/auth.ts", True),
        ("**/middleware/**", "src/middleware/auth.ts", True),
        ("**/middleware/**", "src/mymiddleware/auth.ts", False),
        ("**/*.middleware.*", "src/auth.middleware.ts", True),
        ("**/*Controller.*", "src/Web/UserController.cs", True),
        ("middleware.ts", "middleware.ts", True),
        ("middleware.ts", "src/middleware.ts", False),
        ("app/Http/Middleware/**", "app/http/middleware/Auth.php", True),
        ("src/*.ts", "src/a/b.ts", False),
        ("src\\**", "src/a/b.ts", True),
    ]

    def test_globs_span_directories_only_where_asked(self):
        for pattern, path, expected in self.CASES:
            with self.subTest(pattern=pattern, path=path):
                self.assertEqual(project_files.glob_match(pattern, path), expected)

    def test_read_text_drops_a_byte_order_mark(self):
        import tempfile
        from pathlib import Path
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "a.cs"
            path.write_bytes(b"\xef\xbb\xbfnamespace X;\n")
            self.assertEqual(project_files.read_text(path), "namespace X;\n")

    def test_generated_files_are_recognised_by_name_or_header(self):
        self.assertTrue(project_files.is_generated("Properties/Resources.Designer.cs", "class R {}"))
        self.assertTrue(project_files.is_generated("api/client.g.ts", ""))
        self.assertTrue(project_files.is_generated("proto/order_pb2.py", ""))
        self.assertTrue(project_files.is_generated(
            "src/api.ts", "// Code generated by openapi-generator. DO NOT EDIT.\nexport {}"))
        self.assertFalse(project_files.is_generated("src/designer.ts", "export const a = 1;"))

    def test_literal_weight_ranks_the_more_specific_pattern_higher(self):
        self.assertEqual(project_files.literal_weight("**/middleware/**"), 10)
        self.assertEqual(project_files.literal_weight("**/*.middleware.*"), 12)


if __name__ == "__main__":
    unittest.main()
