import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import support  # noqa: F401  (puts the scripts folder on sys.path)
from source import files as project_files


def make_tree(files: dict) -> tempfile.TemporaryDirectory:
    """A temporary directory populated with the given relative-path -> content files."""
    directory = tempfile.TemporaryDirectory()
    for relative_path, text in files.items():
        target = Path(directory.name) / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    return directory


GIT_ON_PATH = shutil.which("git") is not None


class GitRepoTestCase(unittest.TestCase):
    """A TestCase whose tests run inside a temporary git repository, isolated from
    whatever global or system git config happens to be installed on the machine
    running them.
    """

    @classmethod
    def setUpClass(cls):
        if not GIT_ON_PATH:
            raise unittest.SkipTest("git is not on PATH")

    def setUp(self):
        empty_config = tempfile.NamedTemporaryFile(
            mode="w", suffix=".gitconfig", delete=False)
        empty_config.close()
        self.addCleanup(os.unlink, empty_config.name)
        env_patch = mock.patch.dict(os.environ, {
            "GIT_CONFIG_GLOBAL": empty_config.name,
            "GIT_CONFIG_SYSTEM": empty_config.name,
        })
        env_patch.start()
        self.addCleanup(env_patch.stop)

    def git(self, *args, cwd):
        subprocess.run(["git", *args], cwd=cwd, check=True,
                        capture_output=True, timeout=10)

    def init_repo(self, files: dict, deleted: tuple = ()) -> tempfile.TemporaryDirectory:
        """A temporary git repository with `files` staged and any `deleted` paths
        removed from the working tree afterwards, so they stay in the index only.
        """
        directory = make_tree(files)
        self.git("init", cwd=directory.name)
        if files:
            self.git("add", "-A", cwd=directory.name)
        for relative_path in deleted:
            (Path(directory.name) / relative_path).unlink()
        return directory

    def assert_git_walk_used(self, root):
        """Proves the test exercises the git-backed walk, not the `os.walk` fallback:
        a test that never checks this could pass the same way on either path.
        """
        self.assertIsNotNone(
            project_files._walk_git(Path(root), None, frozenset()),
            "expected the git-backed walk to be usable for this root")


class GlobMatchTest(unittest.TestCase):
    CASES = [
        ("**/middleware/**", "middleware/auth.ts", True),
        ("**/middleware/**", "src/middleware/auth.ts", True),
        ("**/middleware/**", "src/mymiddleware/auth.ts", False),
        ("**/*.middleware.*", "src/auth.middleware.ts", True),
        ("**/*Controller.*", "src/Web/UserController.cs", True),
        ("middleware.ts", "middleware.ts", True),
        ("middleware.ts", "src/middleware.ts", False),
        ("app/Http/Middleware/**", "app/http/middleware/Auth.php", True),
        ("src/*.ts", "src/a/b.ts", False),
        ("src\\**", "src/a/b.ts", True),
    ]

    def test_globs_span_directories_only_where_asked(self):
        for pattern, path, expected in self.CASES:
            with self.subTest(pattern=pattern, path=path):
                self.assertEqual(project_files.glob_match(pattern, path), expected)

    def test_read_text_drops_a_byte_order_mark(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "a.cs"
            path.write_bytes(b"\xef\xbb\xbfnamespace X;\n")
            self.assertEqual(project_files.read_text(path), "namespace X;\n")

    def test_generated_files_are_recognised_by_name_or_header(self):
        self.assertTrue(project_files.is_generated("Properties/Resources.Designer.cs", "class R {}"))
        self.assertTrue(project_files.is_generated("api/client.g.ts", ""))
        self.assertTrue(project_files.is_generated("proto/order_pb2.py", ""))
        self.assertTrue(project_files.is_generated(
            "src/api.ts", "// Code generated by openapi-generator. DO NOT EDIT.\nexport {}"))
        self.assertFalse(project_files.is_generated("src/designer.ts", "export const a = 1;"))

    def test_minified_and_bundled_files_are_generated(self):
        # One 1.7 MB bundle once filled the naming findings with 57,300 one-letter names.
        for path in ("assets/app.min.js", "assets/site.min.css", "assets/vendor.bundle.js", "assets/esm.min.mjs"):
            with self.subTest(path=path):
                self.assertTrue(project_files.is_generated(path, "var a=1;"))
        self.assertFalse(project_files.is_generated("src/admin.js", "var a=1;"))

    def test_a_generated_marker_counts_only_in_the_comment_that_opens_the_file(self):
        generated = [
            ("api/order.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage order\n"),
            ("shop/0001_initial.py", "# -*- coding: utf-8 -*-\n# Generated by Django 5.1 on 2026-01-02 10:00\n\n"
                                     "from django.db import migrations\n"),
            ("api/pet.ts", "/*\n * Petstore API\n * NOTE: This class is auto generated by OpenAPI Generator.\n"
                           " * Do not edit the class manually.\n */\nexport class Pet {}\n"),
            ("app/Api.php", "<?php\n\n// @generated by a tool\nnamespace App;\n"),
            ("App/Model.cs", "// Copyright 2026 Acme\n\n// <auto-generated/>\nusing System;\n"),
            ("App/Model.cs", "#pragma warning disable\n// <auto-generated/>\nnamespace App;\n"),
            # Strong markers also count in a Python module docstring and a PowerShell help block.
            ("client/models/pet.py", '# coding: utf-8\n\n"""\n    Petstore API\n\n'
                                     "    Generated by OpenAPI Generator (https://openapi-generator.tech)\n\n"
                                     '    Do not edit the class manually.\n"""  # noqa: E501\n\nimport pprint\n'),
            ("tools/Deploy.ps1", "<#\n.SYNOPSIS\n    This file is auto-generated by the build.\n#>\nparam()\n"),
            ("tools/sync.sh", "#!/bin/sh\n#Generated by mytool\nset -e\n"),
        ]
        hand_written = [
            ("app/services/invoices.py", '"""Monthly invoices generated by the billing run, and their totals."""\n\n'
                                         "class InvoiceService:\n    pass\n"),
            ("src/note.ts", "export const note = 'this file is auto-generated';\n"),
            ("app/build.py", "import os\n# generated by the build step\nx = 1\n"),
            ("src/version.c", '#include "version_autogenerated.h"\nint main(void) { return 0; }\n'),
            ("src/limits.h", "#define AUTOGENERATED_LIMIT 4\nint limit(void);\n"),
            ("tools/Deploy.ps1", "<#\n.SYNOPSIS\n    Deploys the builds generated by the CI run.\n#>\nparam()\n"),
        ]
        for path, text in generated:
            with self.subTest(path=path, text=text):
                self.assertTrue(project_files.is_generated(path, text))
        for path, text in hand_written:
            with self.subTest(path=path, text=text):
                self.assertFalse(project_files.is_generated(path, text))

    def test_literal_weight_ranks_the_more_specific_pattern_higher(self):
        self.assertEqual(project_files.literal_weight("**/middleware/**"), 10)
        self.assertEqual(project_files.literal_weight("**/*.middleware.*"), 12)


class TestPathTest(unittest.TestCase):
    def test_a_dotnet_test_project_holds_tests(self):
        for folder in ("Shop.Tests", "Shop.UnitTests", "Shop.IntegrationTests", "Shop.IntegrationTest", "Shop.Test"):
            self.assertTrue(project_files.is_test_path(f"{folder}/Helpers/Fixture.cs"), folder)
        self.assertFalse(project_files.is_test_path("Shop.Latest/Order.cs"))
        self.assertFalse(project_files.is_test_path("Shop.Api/Order.cs"))


class JunkDrawerNamesTest(unittest.TestCase):
    def test_one_set_names_the_junk_drawers_for_every_scanner(self):
        import scan_repo
        from structure import organization as structure_organization
        self.assertEqual(project_files.JUNK_DRAWER_NAMES, {
            "utils", "util", "helpers", "helper", "common", "shared", "misc", "miscellaneous", "general",
            "stuff", "core_utils", "lib_utils", "extras"})
        self.assertEqual(scan_repo.find_junk_drawers(["tools/search.py", "tools/fetch.py"]), [])
        self.assertFalse(hasattr(scan_repo, "JUNK_DRAWER_NAMES"))
        self.assertFalse(hasattr(structure_organization, "JUNK_DRAWER_NAMES"))
        self.assertEqual(scan_repo.find_junk_drawers(["general/a.py", "general/b.py"]),
                         [{"directory": "general", "file_count": 2}])


class FrameworkOwnedDirsTest(unittest.TestCase):
    """walk() prunes a framework's own rebuildable or third-party folders."""

    def test_a_unitys_library_files_are_dropped_but_assets_files_are_kept(self):
        with make_tree({
            "Assets/Player.cs": "public class Player {}\n",
            "ProjectSettings/ProjectVersion.txt": "m_EditorVersion: 6000.3.12f1\n",
            "Library/ShaderCache/shader.bin": "binary\n",
        }) as directory:
            result = project_files.walk(Path(directory))
        self.assertIn("Assets/Player.cs", result.paths)
        self.assertIn("ProjectSettings/ProjectVersion.txt", result.paths)
        self.assertFalse(any(path.startswith("Library/") for path in result.paths))

    def test_a_library_folder_without_unitys_siblings_is_kept(self):
        with make_tree({"Library/catalog.txt": "not a unity project\n"}) as directory:
            result = project_files.walk(Path(directory))
        self.assertIn("Library/catalog.txt", result.paths)

    def test_a_drupal_docroot_drops_core_and_contrib_but_keeps_custom(self):
        with make_tree({
            "web/core/core.php": "<?php\n",
            "web/modules/contrib/foo/foo.info.yml": "name: Foo\n",
            "web/modules/custom/greeting/greeting.info.yml": "name: Greeting\n",
            "web/sites/default/settings.php": "<?php\n",
        }) as directory:
            result = project_files.walk(Path(directory))
        self.assertNotIn("web/core/core.php", result.paths)
        self.assertNotIn("web/modules/contrib/foo/foo.info.yml", result.paths)
        self.assertIn("web/modules/custom/greeting/greeting.info.yml", result.paths)

    def test_flutters_generated_ephemeral_folders_are_skipped(self):
        with make_tree({
            "windows/flutter/ephemeral/cpp_client_wrapper/include/flutter/event_channel.h": "class E {};\n",
            "ios/Flutter/ephemeral/flutter_lldbinit": "\n",
            "windows/runner/main.cpp": "int main() { return 0; }\n",
        }) as directory:
            result = project_files.walk(Path(directory))
        self.assertEqual(result.paths, ["windows/runner/main.cpp"])

    def test_an_ephemeral_folder_outside_flutters_is_the_projects_own(self):
        with make_tree({
            "lib/ephemeral/session.dart": "class Session {}\n",
            "linux/flutter/ephemeral/generated_config.cmake": "set(A 1)\n",
        }) as directory:
            result = project_files.walk(Path(directory))
        self.assertEqual(result.paths, ["lib/ephemeral/session.dart"])

    def test_wordpress_core_directories_are_skipped(self):
        with make_tree({
            "wp-includes/functions.php": "<?php\n",
            "wp-admin/index.php": "<?php\n",
            "wp-content/plugins/hello/hello.php": "<?php\n",
        }) as directory:
            result = project_files.walk(Path(directory))
        self.assertNotIn("wp-includes/functions.php", result.paths)
        self.assertNotIn("wp-admin/index.php", result.paths)
        self.assertIn("wp-content/plugins/hello/hello.php", result.paths)


class GitBackedWalkTest(GitRepoTestCase):
    """walk() reads a git work tree through `git ls-files`, so ignored folders drop
    out without SKIP_DIRS or the framework-owned rules having to know about them.
    """

    def test_an_ignored_folder_is_left_out(self):
        with self.init_repo({
            ".gitignore": "ignored/\n",
            "ignored/secret.py": "token = 1\n",
            "kept.py": "value = 1\n",
        }) as directory:
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertIn("kept.py", result.paths)
        self.assertNotIn("ignored/secret.py", result.paths)

    def test_an_untracked_non_ignored_file_is_included(self):
        with self.init_repo({".gitignore": "ignored/\n", "tracked.py": "value = 1\n"}) as directory:
            (Path(directory) / "untracked.py").write_text("value = 2\n", encoding="utf-8")
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertIn("tracked.py", result.paths)
        self.assertIn("untracked.py", result.paths)

    def test_a_deleted_tracked_file_is_not_listed(self):
        with self.init_repo(
            {"gone.py": "value = 1\n", "kept.py": "value = 2\n"}, deleted=("gone.py",),
        ) as directory:
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertNotIn("gone.py", result.paths)
        self.assertIn("kept.py", result.paths)

    def test_a_conflicted_file_is_listed_once(self):
        with self.init_repo({"a.py": "value = 0\n", "b.py": "value = 1\n"}) as directory:
            self.git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", "base",
                     cwd=directory)
            self.git("checkout", "-q", "-b", "side", cwd=directory)
            (Path(directory) / "a.py").write_text("value = 1\n", encoding="utf-8")
            self.git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-am", "side",
                     cwd=directory)
            self.git("checkout", "-q", "-", cwd=directory)
            (Path(directory) / "a.py").write_text("value = 2\n", encoding="utf-8")
            self.git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-am", "main",
                     cwd=directory)
            subprocess.run(["git", "merge", "side"], cwd=directory, capture_output=True, timeout=10)
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertEqual(sorted(result.paths), ["a.py", "b.py"])

    def test_a_folder_whose_files_are_all_ignored_maps_nothing(self):
        with self.init_repo({".gitignore": "data/*\n", "app.py": "value = 1\n"}) as directory:
            (Path(directory) / "data").mkdir()
            (Path(directory) / "data" / "dump.py").write_text("value = 2\n", encoding="utf-8")
            result = project_files.walk(Path(directory) / "data")
        self.assertEqual(result.paths, [])

    def test_a_subfolder_root_lists_paths_relative_to_itself(self):
        with self.init_repo({
            "outer.py": "value = 1\n",
            "sub/inner.py": "value = 2\n",
            "sub/deeper/leaf.py": "value = 3\n",
        }) as directory:
            self.assert_git_walk_used(Path(directory) / "sub")
            result = project_files.walk(Path(directory) / "sub")
        self.assertEqual(sorted(result.paths), ["deeper/leaf.py", "inner.py"])

    def test_skip_dirs_still_prune_a_tracked_node_modules_file(self):
        with self.init_repo({
            "node_modules/pkg/index.js": "module.exports = 1;\n",
            "app.js": "console.log(1);\n",
        }) as directory:
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertIn("app.js", result.paths)
        self.assertFalse(any(path.startswith("node_modules/") for path in result.paths))

    def test_a_non_repository_folder_still_walks_with_os_walk(self):
        with make_tree({"a.py": "value = 1\n", "sub/b.py": "value = 2\n"}) as directory:
            with mock.patch.dict(os.environ,
                                  {"GIT_CEILING_DIRECTORIES": str(Path(directory).parent)}):
                self.assertIsNone(project_files._walk_git(Path(directory), None, frozenset()),
                                  "expected no repository to be found above this folder")
                result = project_files.walk(Path(directory))
        self.assertEqual(sorted(result.paths), ["a.py", "sub/b.py"])

    def test_a_root_ignored_by_an_enclosing_repository_falls_back_to_os_walk(self):
        # The root itself is entirely invisible to git (`.gitignore: project/`), so
        # `git ls-files` returns nothing for it even though it plainly has files.
        with make_tree({
            ".gitignore": "project/\n",
            "project/app.py": "value = 1\n",
        }) as directory:
            self.git("init", cwd=directory)
            self.git("add", "-A", cwd=directory)
            root = Path(directory) / "project"
            self.assertIsNone(project_files._walk_git(root, None, frozenset()),
                               "expected the ignored root to make the git path unusable")
            result = project_files.walk(root)
        self.assertEqual(result.paths, ["app.py"])

    def test_a_submodule_gitlinks_files_are_still_walked(self):
        with self.init_repo({"app.py": "value = 1\n"}) as directory:
            submodule_dir = Path(directory) / "libs" / "sub"
            submodule_dir.mkdir(parents=True)
            (submodule_dir / "mod.py").write_text("value = 2\n", encoding="utf-8")
            self.git("update-index", "--add", "--cacheinfo", f"160000,{'a' * 40},libs/sub",
                      cwd=directory)
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertIn("app.py", result.paths)
        self.assertIn("libs/sub/mod.py", result.paths)

    def test_an_untracked_nested_repositorys_files_are_still_walked(self):
        with self.init_repo({"app.py": "value = 1\n"}) as directory:
            nested_dir = Path(directory) / "inner"
            nested_dir.mkdir()
            self.git("init", cwd=nested_dir)
            (nested_dir / "mod.py").write_text("value = 2\n", encoding="utf-8")
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertIn("app.py", result.paths)
        self.assertIn("inner/mod.py", result.paths)

    def test_a_root_named_flutter_still_prunes_its_own_ephemeral_folder(self):
        # The framework-owned rule keys off the containing directory's own name; a
        # git-tree root has no ancestor path to read that from, unlike `os.walk`.
        with self.init_repo({
            "flutter/ephemeral/generated_config.cmake": "set(A 1)\n",
            "flutter/runner/main.cpp": "int main() { return 0; }\n",
        }) as directory:
            flutter_root = Path(directory) / "flutter"
            self.assert_git_walk_used(flutter_root)
            result = project_files.walk(flutter_root)
        self.assertEqual(result.paths, ["runner/main.cpp"])

    def test_an_empty_required_sibling_still_counts_for_pruning(self):
        # git never lists an empty directory, so "sites" would be invisible to a
        # walk built only from git's file list; the Drupal rule still needs it.
        with self.init_repo({
            "web/core/core.php": "<?php\n",
            "web/modules/custom/greeting/greeting.info.yml": "name: Greeting\n",
        }) as directory:
            (Path(directory) / "web" / "sites").mkdir(parents=True)
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertNotIn("web/core/core.php", result.paths)
        self.assertIn("web/modules/custom/greeting/greeting.info.yml", result.paths)

    def test_the_cap_still_applies_and_reports_truncation_through_the_git_path(self):
        files = {f"file_{index:03d}.py": "value = 1\n" for index in range(5)}
        with self.init_repo(files) as directory:
            self.assert_git_walk_used(directory)
            with mock.patch.object(project_files, "MAX_FILES_SCANNED", 3):
                result = project_files.walk(Path(directory))
        self.assertEqual(len(result.paths), 3)
        self.assertTrue(result.truncated)

    def test_order_matches_os_walk_not_a_flat_path_sort(self):
        # `os.walk` visits a directory's own files before its subdirectories, so
        # "a/z.py" comes before "a/b/x.py" - the opposite of a flat alphabetical sort.
        with self.init_repo({
            "a/z.py": "value = 1\n",
            "a/b/x.py": "value = 2\n",
        }) as directory:
            self.assert_git_walk_used(directory)
            result = project_files.walk(Path(directory))
        self.assertEqual(result.paths, ["a/z.py", "a/b/x.py"])


class GitMissingFallbackTest(unittest.TestCase):
    """No real git repository needed: `subprocess.run` is replaced outright to
    simulate `git` not being installed, so this runs even where git is unavailable.
    """

    def test_a_missing_git_binary_falls_back_to_os_walk(self):
        with make_tree({"a.py": "value = 1\n"}) as directory:
            with mock.patch("source.files.subprocess.run", side_effect=FileNotFoundError):
                result = project_files.walk(Path(directory))
        self.assertEqual(result.paths, ["a.py"])


if __name__ == "__main__":
    unittest.main()
