import contextlib
import io
import json
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest import mock

import support  # puts the scripts folder on sys.path
import map_structure
import project_files
import project_symbols
import structure_report

FIXTURE = {
    "package.json": '{"dependencies": {"express": "4.19.2"}}\n',
    ".clean/roles.md": """
        ```clean-roles
        role middleware = **/middleware/**
        role service = **/services/**
        role route = **/routes/**
        signal middleware = \\(\\s*req\\b[^)]*,\\s*res\\b[^)]*,\\s*next\\b
        name service = Service$
        ```
        """,
    "src/app.js": """
        const users = require('./routes/users');
        const requestId = require('./middleware/requestId');
        """,
    "src/routes/users.js": """
        const auth = require('../services/auth');
        """,
    "src/middleware/requestId.js": """
        /** Tags each request with an id. */
        module.exports = function requestId(req, res, next) { next(); };
        """,
    "src/services/auth.js": """
        // Issues and checks session tokens.

        class AuthService {}
        function authMiddleware(req, res, next) { next(); }
        module.exports = { AuthService, authMiddleware };
        """,
    "src/services/client.generated.js": """
        // Code generated by a tool. DO NOT EDIT.
        function clientMiddleware(req, res, next) { next(); }
        module.exports = { clientMiddleware };
        """,
    "src/services/fetch.js": """
        function getUser(id) { return id; }
        function fetchUser(id) { return id; }
        module.exports = { getUser, fetchUser };
        """,
}


def write_fixture(root: Path, files: dict) -> None:
    for path, text in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(textwrap.dedent(text).lstrip("\n"), encoding="utf-8")


def build_fixture(files: dict, packs: list) -> dict:
    """The structure map of a throwaway project holding files, under the given packs."""
    with tempfile.TemporaryDirectory() as directory:
        write_fixture(Path(directory), files)
        return map_structure.build_map(Path(directory), packs=packs, depth=2)


def run(*argv):
    output = io.StringIO()
    with contextlib.redirect_stdout(output), contextlib.redirect_stderr(io.StringIO()):
        code = map_structure.main(list(argv))
    return code, output.getvalue()


class ClosedPipe(io.StringIO):
    """A stdout whose reader went away, as when the output is piped into `head`."""

    def write(self, text):
        raise BrokenPipeError(32, "Broken pipe")


class MapStructureTest(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.root = Path(self.directory.name)
        write_fixture(self.root, FIXTURE)

    def tearDown(self):
        self.directory.cleanup()

    def test_the_middleware_in_the_service_file_is_misplaced(self):
        data = map_structure.build_map(self.root, packs=[], depth=2)
        misplaced = data["findings"]["misplaced"]
        self.assertEqual(len(misplaced), 1)
        self.assertEqual(misplaced[0]["symbol"], "authMiddleware")
        self.assertEqual(misplaced[0]["suggestion"], "src/middleware/")

    def test_suggestions_stay_inside_the_project_that_holds_the_file(self):
        write_fixture(self.root, {
            "Billing/Billing.csproj": "<Project Sdk=\"Microsoft.NET.Sdk\" />\n",
            "Billing/Services/InvoiceService.cs": """
                namespace Billing.Services;
                public class InvoiceService {}
                public class InvoiceValidator {}
                """,
            "Shared/Shared.csproj": "<Project Sdk=\"Microsoft.NET.Sdk\" />\n",
            "Shared/Validators/NameValidator.cs": """
                namespace Shared.Validators;
                public class NameValidator {}
                """,
        })
        roles = ".clean/roles.md"
        (self.root / roles).write_text(
            "```clean-roles\nrole service = **/Services/**\nname service = Service$\n"
            "role validator = **/Validators/**\nname validator = Validator$\n```\n",
            encoding="utf-8")
        data = map_structure.build_map(self.root, packs=[], depth=2)
        found = [item for item in data["findings"]["misplaced"] if item["symbol"] == "InvoiceValidator"]
        self.assertEqual([item["suggestion"] for item in found], ["Billing/Validators/"])

    def test_a_route_folder_is_no_home_to_move_a_file_into(self):
        # `page.tsx` is a component home by its file name; `orders/` is a route, not a home.
        data = build_fixture({
            "package.json": '{"dependencies": {"next": "15.5.0", "react": "19.0.0"}}\n',
            "src/app/layout.tsx": "import { Providers } from './providers';\n"
                                  "export default function RootLayout() { return null; }\n",
            "src/app/providers.tsx": "'use client';\n"
                                     "export function Providers() { return null; }\n",
            "src/app/orders/page.tsx": "export default function OrdersPage() { return null; }\n",
            "src/app/orders/OrderTable.tsx": "export function OrderTable() { return null; }\n",
        }, ["references/frameworks/nextjs.md", "references/frameworks/react.md"])
        self.assertEqual(data["findings"]["misplaced"], [])

    def test_a_feature_package_is_no_home_to_move_a_file_into(self):
        # `BillingService.java` is a service home by its file name; `billing/` is a feature.
        shop = "src/main/java/com/acme/shop"
        data = build_fixture({
            f"{shop}/billing/BillingService.java":
                "package com.acme.shop.billing;\n\n@Service\npublic class BillingService {}\n",
            f"{shop}/Notifications.java":
                "package com.acme.shop;\n\n@Service\npublic class Notifications {}\n",
        }, ["references/frameworks/spring.md"])
        self.assertEqual(data["findings"]["misplaced"], [])

    def test_a_django_model_in_a_view_moves_to_the_models_module_beside_it(self):
        data = build_fixture({
            "requirements.txt": "Django==5.2\n",
            "shop/billing/models.py": "from django.db import models\n\n\n"
                                      "class Invoice(models.Model):\n    total = models.IntegerField()\n",
            "shop/orders/models.py": "from django.db import models\n\n\n"
                                     "class Order(models.Model):\n    total = models.IntegerField()\n",
            "shop/orders/views.py": "from django.db import models\nfrom django.views import View\n\n\n"
                                    "class OrderListView(View):\n    def get(self, request):\n"
                                    "        return None\n\n\n"
                                    "class Refund(models.Model):\n    amount = models.IntegerField()\n",
        }, ["references/frameworks/django.md"])
        self.assertEqual([(item["path"], item["symbol"], item["suggestion"])
                          for item in data["findings"]["misplaced"]],
                         [("shop/orders/views.py", "Refund", "shop/orders/models.py")])

    def test_a_spring_service_in_a_feature_package_gets_its_own_file_there(self):
        order = "src/main/java/com/acme/shop/order"
        data = build_fixture({
            "pom.xml": "<project><dependencies><dependency><groupId>org.springframework.boot</groupId>"
                       "<artifactId>spring-boot-starter-web</artifactId></dependency></dependencies></project>\n",
            "src/main/java/com/acme/shop/billing/BillingService.java":
                "package com.acme.shop.billing;\n\n@Service\npublic class BillingService {\n"
                "  public void charge() { }\n}\n",
            f"{order}/OrderController.java":
                "package com.acme.shop.order;\n\n@RestController\npublic class OrderController {\n"
                "  public String list() { return \"x\"; }\n}\n\n@Service\nclass OrderPricing {\n"
                "  int price() { return 1; }\n}\n",
            f"{order}/OrderService.java":
                "package com.acme.shop.order;\n\n@Service\npublic class OrderService {\n"
                "  public void place() { }\n}\n",
        }, ["references/frameworks/spring.md"])
        self.assertEqual([(item["path"], item["symbol"], item["suggestion"])
                          for item in data["findings"]["misplaced"]],
                         [(f"{order}/OrderController.java", "OrderPricing", f"{order}/*Service.*")])
        self.assertIn(f"move it to its own file named like *Service.* in {order}/.",
                      structure_report.render_summary(data))

    def test_an_angular_service_in_a_component_gets_its_own_file_in_the_feature_folder(self):
        data = build_fixture({
            "package.json": '{"dependencies": {"@angular/core": "20.1.0"}}\n',
            "src/app/orders/orders.component.ts":
                "import { Component, Injectable } from '@angular/core';\n\n"
                "@Component({ selector: 'app-orders', template: '' })\nexport class OrdersComponent {}\n\n"
                "@Injectable({ providedIn: 'root' })\nexport class OrdersApi {\n  load() { return []; }\n}\n",
            "src/app/users/users.service.ts":
                "import { Injectable } from '@angular/core';\n\n@Injectable({ providedIn: 'root' })\n"
                "export class UsersService {\n  load() { return []; }\n}\n",
        }, ["references/frameworks/angular.md"])
        self.assertEqual([(item["path"], item["symbol"], item["suggestion"])
                          for item in data["findings"]["misplaced"]],
                         [("src/app/orders/orders.component.ts", "OrdersApi", "src/app/orders/*.service.*")])

    def test_a_folder_home_counts_when_its_files_are_also_named_for_the_role(self):
        data = build_fixture({
            "src/app/services/user.service.ts": "export class UserService {}\n",
            "src/app/orders/orders.controller.ts":
                "export class OrdersController {}\nexport class OrdersService {}\n",
        }, [])
        self.assertEqual([(item["symbol"], item["suggestion"]) for item in data["findings"]["misplaced"]],
                         [("OrdersService", "src/app/services/")])

    def test_a_react_context_module_holds_its_provider_and_hook(self):
        data = build_fixture({
            "src/contexts/AuthContext.tsx":
                "import { createContext, useContext, useState } from 'react';\n\n"
                "export const AuthContext = createContext<string | null>(null);\n\n"
                "export function AuthProvider({ children }: { children: React.ReactNode }) {\n"
                "  const [user] = useState<string | null>(null);\n"
                "  return <AuthContext.Provider value={user}>{children}</AuthContext.Provider>;\n}\n\n"
                "export function useAuth() {\n  return useContext(AuthContext);\n}\n",
            "src/components/Avatar.tsx": "export function Avatar() { return null; }\n"
                                         "export function useAvatarUrl() { return ''; }\n",
            "src/hooks/useDebounce.ts": "export function useDebounce<T>(value: T) { return value; }\n",
        }, ["references/frameworks/react.md"])
        self.assertEqual([(item["symbol"], item["suggestion"]) for item in data["findings"]["misplaced"]],
                         [("useAvatarUrl", "src/hooks/")])

    def test_express_middleware_in_a_service_moves_to_the_middleware_home(self):
        # A handler taking `next` stays unflagged in its controller or route home.
        data = build_fixture({
            "package.json": '{"dependencies": {"express": "4.21.2"}}\n',
            "src/middleware/cors.ts": "export function cors(req: any, res: any, next: any) { next(); }\n",
            "src/services/Auth.ts":
                "export class AuthService {\n  verify(token: string) { return token.length > 0; }\n}\n"
                "export function requireAuth(req: any, res: any, next: any) {\n"
                "  if (!req.headers.authorization) return res.status(401).end();\n  next();\n}\n",
            "src/controllers/users.js":
                "async function getUser(req, res, next) {\n"
                "  try { res.json({ id: req.params.id }); } catch (error) { next(error); }\n}\n"
                "module.exports = { getUser };\n",
            "src/routes/health.js": "function health(req, res, next) { res.send('ok'); }\n"
                                    "module.exports = { health };\n",
            # Express 4 handlers in a homeless module: not middleware to move whole.
            "src/users.js": "async function getUsers(req, res, next) {\n"
                            "  try { res.json([]); } catch (error) { next(error); }\n}\n"
                            "async function getUser(req, res, next) {\n"
                            "  try { res.json({}); } catch (error) { next(error); }\n}\n"
                            "module.exports = { getUsers, getUser };\n",
        }, ["references/frameworks/express.md"])
        self.assertEqual([(item["path"], item["symbol"], item["suggestion"])
                          for item in data["findings"]["misplaced"]],
                         [("src/services/Auth.ts", "requireAuth", "src/middleware/")])

    def test_the_project_records_a_placement_exception_with_accept(self):
        files = {
            "src/middleware/cors.js": "module.exports = function cors(req, res, next) { next(); };\n",
            "src/services/auth.js": "class AuthService {}\n"
                                    "function handleAuthError(err, req, res, next) { next(err); }\n"
                                    "module.exports = { AuthService, handleAuthError };\n",
        }
        packs = ["references/frameworks/express.md"]
        flagged = build_fixture(files, packs)["findings"]["misplaced"]
        self.assertEqual([item["symbol"] for item in flagged], ["handleAuthError"])
        files[".clean/roles.md"] = ("Recorded in decisions.md: the auth error handler stays with auth.\n\n"
                                    "```clean-roles\naccept src/services/auth.js = handleAuthError\n```\n")
        self.assertEqual(build_fixture(files, packs)["findings"]["misplaced"], [])

    def test_one_walk_finds_the_sources_and_the_projects(self):
        write_fixture(self.root, {
            "Audit/Audit.csproj": "<Project Sdk=\"Microsoft.NET.Sdk\" />\n",
            "Audit/Database.cs": "namespace Audit;\npublic class Database {}\n",
            "State/State.csproj": "<Project Sdk=\"Microsoft.NET.Sdk\" />\n",
            "State/Database.cs": "namespace State;\npublic class Database {}\n",
            "State/Legacy/Database.cs": "namespace State.Legacy;\npublic class Database {}\n",
        })
        with mock.patch.object(project_files, "walk", side_effect=project_files.walk) as walk:
            data = map_structure.build_map(self.root, packs=[], depth=2)
        self.assertEqual(walk.call_count, 1)
        self.assertEqual([[member["path"] for member in group["members"]]
                          for group in data["findings"]["name_clashes"]],
                         [["State/Database.cs", "State/Legacy/Database.cs"]])

    def test_synonyms_imports_and_purposes_are_recorded(self):
        data = map_structure.build_map(self.root, packs=[], depth=2)
        self.assertEqual([item["noun"] for item in data["findings"]["synonyms"]], ["user"])
        files = {entry["path"]: entry for entry in data["files"]}
        self.assertEqual(files["src/app.js"]["imports"],
                         ["src/middleware/requestId.js", "src/routes/users.js"])
        self.assertEqual(files["src/services/auth.js"]["purpose"], "Issues and checks session tokens.")
        self.assertEqual(files["src/services/auth.js"]["role"], "service")
        self.assertIn({"from": "src", "to": "src/routes", "count": 1}, data["edges"])
        self.assertNotIn("src/services/client.generated.js", files)

    def test_markdown_orders_sections_for_partial_reads(self):
        markdown = structure_report.render_markdown(
            map_structure.build_map(self.root, packs=[], depth=2), top=25)
        positions = [markdown.index(heading) for heading in
                     ("## Findings", "## Tree", "## Components", "## Files")]
        self.assertEqual(positions, sorted(positions))
        self.assertIn("| `src/services/auth.js` | service |", markdown)
        self.assertIn("`authMiddleware` !", markdown)

    def test_write_saves_both_files(self):
        code, output = run("--root", str(self.root), "--write")
        self.assertEqual(code, 0)
        self.assertTrue((self.root / ".clean" / "structure.md").is_file())
        data = json.loads((self.root / ".clean" / "structure.json").read_text(encoding="utf-8"))
        self.assertEqual(data["schema_version"], 1)
        self.assertIn("Saved", output)

    def test_path_limits_the_summary_to_a_folder(self):
        code, output = run("--root", str(self.root), "--path", "src/services")
        self.assertEqual(code, 0)
        self.assertIn("src/services/auth.js", output)
        self.assertNotIn("src/app.js", output)

    def test_recorded_pack_scopes_travel_with_the_recorded_packs(self):
        (self.root / ".clean" / "context.json").write_text(json.dumps({
            "packs": ["references/frameworks/react.md"],
            "pack_scopes": {"references/frameworks/react.md": ["web"]},
        }), encoding="utf-8")
        self.assertEqual(map_structure.stack_for(self.root, None),
                         (["references/frameworks/react.md"],
                          {"references/frameworks/react.md": ["web"]}))
        self.assertEqual(map_structure.stack_for(self.root, "frameworks/react.md"),
                         (["references/frameworks/react.md"], {}))

    def test_system_includes_draw_no_edges(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_fixture(root, {
                "src/net/ssl.h": "int ssl_init(void);\n",
                "src/core/time.h": "int now(void);\n",
                "src/app/main.c": "#include <openssl/ssl.h>\n#include <sys/time.h>\n"
                                  "int main(void)\n{\n    return 0;\n}\n",
            })
            data = map_structure.build_map(root, packs=[], depth=2)
        files = {entry["path"]: entry for entry in data["files"]}
        self.assertEqual(files["src/app/main.c"]["imports"], [])
        self.assertEqual(data["edges"], [])

    def test_a_console_that_cannot_encode_a_character_still_gets_the_map(self):
        (self.root / "src" / "services" / "orders.js").write_text(
            "// Zeigt Bestellungen an → JSON (订单).\n\nfunction listOrders() {}\n"
            "module.exports = { listOrders };\n", encoding="utf-8")
        code, output = support.run_on_ansi_console(
            map_structure.main, ["--root", str(self.root), "--path", "src/services", "--write"])
        self.assertEqual(code, 0)
        self.assertIn("订单", output)
        self.assertTrue((self.root / ".clean" / "structure.json").is_file())
        code, output = support.run_on_ansi_console(map_structure.main, ["--root", str(self.root), "--json"])
        self.assertEqual(code, 0)
        files = {entry["path"]: entry for entry in json.loads(output)["files"]}
        self.assertIn("→", files["src/services/orders.js"]["purpose"])

    def test_the_map_is_saved_before_anything_is_printed(self):
        with contextlib.redirect_stdout(ClosedPipe()), self.assertRaises(BrokenPipeError):
            map_structure.main(["--root", str(self.root), "--write"])
        self.assertTrue((self.root / ".clean" / "structure.json").is_file())

    def test_a_file_that_cannot_be_read_is_listed_not_fatal(self):
        (self.root / "src" / "legacy.py").write_text("def broken(:\n    pass\n", encoding="utf-8")
        extract = project_symbols.extract

        def fragile_extract(path, text):
            if path == "src/services/fetch.js":
                raise RecursionError("maximum recursion depth exceeded")
            return extract(path, text)

        with mock.patch.object(project_symbols, "extract", side_effect=fragile_extract):
            data = map_structure.build_map(self.root, packs=[], depth=2)
        unparsed = {item["path"]: item["reason"] for item in data["unparsed"]}
        self.assertIn("RecursionError", unparsed["src/services/fetch.js"])
        self.assertIn("SyntaxError", unparsed["src/legacy.py"])
        files = {entry["path"] for entry in data["files"]}
        self.assertEqual(("src/services/fetch.js" in files, "src/legacy.py" in files), (False, True))
        self.assertIn("src/services/auth.js", files)
        header = structure_report.render_markdown(data).split("## Findings")[0]
        self.assertIn("`src/legacy.py`", header)
        self.assertIn("src/services/fetch.js", structure_report.render_summary(data))

    def test_a_malformed_roles_file_is_an_error(self):
        (self.root / ".clean" / "roles.md").write_text("```clean-roles\nnonsense\n```\n",
                                                       encoding="utf-8")
        code, _ = run("--root", str(self.root))
        self.assertEqual(code, 2)


if __name__ == "__main__":
    unittest.main()
