#!/usr/bin/env python3
"""Which files count as the project, decided once for every script in this folder.

detect_stack, scan_repo, and check_boundaries each walk the repository. They
must agree on what to skip (dependency and build folders, dot-directories),
what a test file looks like, and how much to read, or the same project shows
different shapes to different tools. Import from here; do not copy.

Standard library only. Reads files; never writes.
"""

from __future__ import annotations

import functools
import os
import re
from pathlib import Path
from typing import NamedTuple

# Directories that hold dependencies, build output, or tool caches. Walking them
# is slow and tells us nothing about the project's own design.
SKIP_DIRS = frozenset({
    ".git", ".hg", ".svn", ".idea", ".vscode", ".vs",
    "node_modules", "bower_components", "jspm_packages", "vendor",
    "__pycache__", ".venv", "venv", "env", ".tox", ".nox", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", ".gradle", ".dart_tool", ".terraform",
    "bin", "obj", "build", "dist", "out", "target", "_build", "deps",
    "coverage", "htmlcov", ".next", ".nuxt", ".svelte-kit", ".parcel-cache",
    "Pods", "Carthage", ".cargo", ".stack-work", "cmake-build-debug", "migrations",
    "wp-admin", "wp-includes",
})

# A folder a framework owns, pruned only where the framework's own layout proves it:
# Unity's Library/Temp/Logs/UserSettings are rebuildable caches beside Assets and
# ProjectSettings, a Drupal docroot's composer-installed core, or a modules, themes, or
# profiles folder's composer-installed contrib, are not the project's code, and neither is
# Flutter's generated {windows,linux,macos}/flutter/ephemeral or ios/Flutter/ephemeral.
# (sibling folder names that must all be present, folder names to prune, parent folder
# names one of which must hold them: empty for any)
FRAMEWORK_OWNED_DIRS = (
    (frozenset({"Assets", "ProjectSettings"}), frozenset({"Library", "Temp", "Logs", "UserSettings"}),
     frozenset()),
    (frozenset({"core", "modules", "sites"}), frozenset({"core"}), frozenset()),
    (frozenset({"contrib", "custom"}), frozenset({"contrib"}), frozenset()),
    (frozenset(), frozenset({"ephemeral"}), frozenset({"flutter", "Flutter"})),
)

TEST_DIR_NAMES = frozenset({
    "test", "tests", "spec", "specs", "__tests__", "testing",
    "unittest", "unittests", "test_suite", "integration-tests",
})

TEST_FILE_PATTERN = re.compile(
    r"(^test_|_test\.|\.test\.|\.spec\.|_spec\.|Tests?\.|Spec\.)", re.IGNORECASE
)
# A .NET test project: `Shop.Tests/`, `Shop.UnitTests/`, `Shop.IntegrationTest/`, `Shop.Test/`.
TEST_PROJECT_PATTERN = re.compile(r"\.(?:Unit|Integration)?Tests?$", re.IGNORECASE)

# Folders named for no concept, a place to put code rather than what the code is about.
# `tools` is left out: it is often the domain word itself (an MCP server's tools, build tooling).
JUNK_DRAWER_NAMES = frozenset({
    "utils", "util", "helpers", "helper", "common", "shared", "misc", "miscellaneous", "general",
    "stuff", "core_utils", "lib_utils", "extras",
})

GENERATED_MARKERS = (
    "generated by", "auto-generated", "autogenerated", "do not edit",
    "code generated by", "@generated",
)
# Prose that may describe the file's own subject, a Python module docstring or PowerShell
# help, says a generator wrote the file only through these: "invoices generated by the
# billing run" is hand-written.
STRONG_GENERATED_MARKERS = ("do not edit", "auto-generated", "autogenerated", "@generated",
                            "code generated by")

# Files a generator owns by name: .NET designers, source generators, protobuf stubs, and
# minified or bundled scripts and styles.
GENERATED_NAME = re.compile(r"\.(?:designer|g|g\.i|generated)\.\w+$|_pb2\.py$|\.pb\.go$"
                            r"|\.min\.(?:js|mjs|css)$|\.bundle\.js$",
                            re.IGNORECASE)
GENERATED_HEAD_LINES = 15

# A generator's header opens the file, before any code: line and block comments, after a
# PHP open tag or, in C-family and C# files, a directive such as `#pragma` or `#include`.
_LINE_COMMENT = re.compile(r"^(?://|--|#)")
_BLOCK_COMMENTS = (("/*", "*/"), ("<!--", "-->"))
_PHP_OPEN_TAG = re.compile(r"^<\?(?:php)?$")
_DIRECTIVE_SUFFIXES = frozenset({".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".hh", ".m", ".mm", ".cs"})
_PYTHON_DOCSTRING = re.compile(r"^[rRuUbB]{0,2}(\"{3}|'{3})")
_PYTHON_SUFFIXES = frozenset({".py", ".pyi"})
_POWERSHELL_SUFFIXES = frozenset({".ps1", ".psm1", ".psd1"})

MAX_FILE_BYTES = 2_000_000
MAX_FILES_SCANNED = 40000


class Walk(NamedTuple):
    """Root-relative posix paths in walk order, and whether the cap cut the walk short."""

    paths: list
    truncated: bool


def is_skippable(directory_name: str) -> bool:
    return directory_name in SKIP_DIRS or (
        directory_name.startswith(".") and directory_name != ".github"
    )


def walk(root: Path, suffixes=None, names=frozenset()) -> Walk:
    """Every project file under root, optionally only those with the given suffixes or names.

    Stops at MAX_FILES_SCANNED and says so, so a caller never mistakes a partial
    walk for the whole project.
    """
    paths: list = []
    for current_dir, subdirs, filenames in os.walk(root):
        sibling_dirs = frozenset(subdirs)
        parent = os.path.basename(current_dir)
        pruned = frozenset().union(*(prune_names for required, prune_names, parents in FRAMEWORK_OWNED_DIRS
                                      if required <= sibling_dirs and (not parents or parent in parents)))
        subdirs[:] = sorted(name for name in subdirs
                             if not is_skippable(name) and name not in pruned)
        for filename in sorted(filenames):
            path = Path(current_dir) / filename
            if suffixes is not None and path.suffix.lower() not in suffixes and filename not in names:
                continue
            if len(paths) >= MAX_FILES_SCANNED:
                return Walk(paths, True)
            try:
                paths.append(path.relative_to(root).as_posix())
            except ValueError:
                continue
    return Walk(paths, False)


def is_test_path(relative_path: str) -> bool:
    parts = relative_path.split("/")
    if any(part.lower() in TEST_DIR_NAMES or TEST_PROJECT_PATTERN.search(part) for part in parts[:-1]):
        return True
    return bool(TEST_FILE_PATTERN.search(parts[-1]))


def _block_opener(stripped: str, suffix: str):
    """(opener, closer, is_prose) when the line opens a block comment, a Python module
    docstring, or a PowerShell `<# #>` help block; else None."""
    for opener, closer in _BLOCK_COMMENTS:
        if stripped.startswith(opener):
            return opener, closer, False
    if suffix in _POWERSHELL_SUFFIXES and stripped.startswith("<#"):
        return "<#", "#>", True
    docstring = _PYTHON_DOCSTRING.match(stripped) if suffix in _PYTHON_SUFFIXES else None
    if docstring:
        return docstring.group(0), docstring.group(1), True
    return None


def _opening_text(text: str, suffix: str) -> tuple:
    """(comments, prose) before a file's first line of code, lowercased.

    Comments are line and block comments; prose is a Python module docstring or a
    PowerShell `<# #>` help block, which may describe the file's own subject.
    """
    comments, prose = [], []
    closer, block = None, comments
    for line in text.lstrip("\ufeff").split("\n", GENERATED_HEAD_LINES)[:GENERATED_HEAD_LINES]:
        stripped = line.strip()
        if closer:
            block.append(stripped)
            closer = None if closer in stripped else closer
            continue
        if not stripped or _PHP_OPEN_TAG.match(stripped):
            continue
        opened = _block_opener(stripped, suffix)
        if opened:
            opener, closer, is_prose = opened
            block = prose if is_prose else comments
            block.append(stripped)
            closer = None if closer in stripped[len(opener):] else closer
        elif stripped.startswith("#") and suffix in _DIRECTIVE_SUFFIXES:
            continue            # a preprocessor directive, not a comment
        elif _LINE_COMMENT.match(stripped):
            comments.append(stripped)
        else:
            break
    return "\n".join(comments).lower(), "\n".join(prose).lower()


def is_generated(relative_path: str, text: str) -> bool:
    """Whether a generator owns the file: by its name, or by a marker in the comment
    that opens it.

    Generated code is not the project's design; judging its structure would only
    report the generator's choices. A marker anywhere else is prose: a docstring
    saying "invoices generated by the billing run" is hand-written code, though one
    saying "do not edit" is not.
    """
    if GENERATED_NAME.search(relative_path):
        return True
    comments, prose = _opening_text(text, Path(relative_path).suffix.lower())
    return (any(marker in comments for marker in GENERATED_MARKERS)
            or any(marker in prose for marker in STRONG_GENERATED_MARKERS))


@functools.lru_cache(maxsize=None)
def _glob_regex(pattern: str) -> re.Pattern:
    normalized = pattern.replace("\\", "/").lower()
    parts = []
    index = 0
    while index < len(normalized):
        if normalized.startswith("**/", index):
            parts.append("(?:.*/)?")
            index += 3
        elif normalized.startswith("/**", index) and index + 3 == len(normalized):
            parts.append("(?:/.*)?")
            index += 3
        elif normalized.startswith("**", index):
            parts.append(".*")
            index += 2
        elif normalized[index] == "*":
            parts.append("[^/]*")
            index += 1
        elif normalized[index] == "?":
            parts.append("[^/]")
            index += 1
        else:
            parts.append(re.escape(normalized[index]))
            index += 1
    return re.compile("^" + "".join(parts) + "$")


def glob_match(pattern: str, relative_path: str) -> bool:
    """Whether a root-relative path matches a glob, ignoring case.

    `**/` spans zero or more directories and a trailing `/**` everything below,
    while `*` and `?` never cross a slash. fnmatch lets `*` cross slashes, which
    makes `**/middleware/**` miss a top-level `middleware/` folder.
    """
    return bool(_glob_regex(pattern).match(relative_path.replace("\\", "/").lower()))


def literal_weight(pattern: str) -> int:
    """How specific a glob is: its characters that are neither wildcards nor slashes."""
    return sum(1 for character in pattern if character not in "*?/\\")


def read_text(path: Path) -> str | None:
    """The file's text, or None when it is unreadable or too large to be source."""
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return None
        # utf-8-sig drops a byte-order mark: Windows tools write one, and it would
        # otherwise sit in front of the first declaration.
        with path.open("r", encoding="utf-8-sig", errors="replace") as handle:
            return handle.read()
    except OSError:
        return None
